# Generated by Django 4.2.4 on 2023-09-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Care_Centre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('date', models.DateField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
