# Generated by Django 4.2.4 on 2023-09-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Care_Centre', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='person_name',
        ),
    ]
